os: linux
dist: trusty
sudo: false

language: cpp

script: ./build.sh -nodep

branches:
  only:
  - master

addons:
  apt:
    packages:
    - ninja-build
    - clang-format
    - libpulse-dev
    - libgtkmm-3.0-dev

