os: linux
dist: trusty
sudo: false

language: cpp

script: ./build.sh -nodep

branches:
  only:
  - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ninja-build
    - libpulse-dev
    - libgtkmm-3.0-dev
    - g++-7

