os: linux
dist: trusty
sudo: false

language: cpp

script: ./build.sh -nodep -compilers "gcc-5 gcc-7 clang" -v -k 99

branches:
  only:
  - master

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - ninja-build
    - g++-5
    - g++-7
    - libpulse-dev
    - libgtkmm-3.0-dev

